# Generated by Django 5.2.9 on 2025-12-24 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(max_length=100, verbose_name="Kategoriya (UZ)"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=100, verbose_name="Kategoriya (RU)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=100, verbose_name="Nomi (UZ)")),
                ("name_ru", models.CharField(max_length=100, verbose_name="Nomi (RU)")),
                ("price", models.PositiveIntegerField(verbose_name="Narxi")),
                ("image", models.ImageField(upload_to="products/")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.category"
                    ),
                ),
            ],
        ),
    ]
